version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:3000"
      - "80:3000"
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true